#!/usr/bin/env bash

# Shows branches with descriptions
show_branches() {
	local cyan
	local green
	local normal
	local branches
	local description
	local format

	cyan=$(tput setaf 6)
	green=$(tput setaf 2)
	normal=$(tput sgr0)
	branches=$(git for-each-ref --format='%(refname)' refs/heads/ | sed 's|refs/heads/||')

	for branch in $branches; do
		description="$cyan$(git config branch."$branch".description)$normal"

		if [ "$branch" == "$(git rev-parse --abbrev-ref HEAD)" ]; then
			format="* $green%-15s$normal %s\\n"
		else
			format="  %-15s %s\\n"
		fi

		# shellcheck disable=SC2059
		printf "${format}" "$branch" "$description"
	done
}

show_branches
