#!/usr/bin/env bash

# Shows branches with descriptions

set -eu

fmt='
	branch="  %(refname:short)"

	%(if)%(HEAD)%(then)
		branch="%(HEAD) %(color:green)%(refname:short)%(color:reset)"
	%(end)

	echo "$branch,%(color:cyan)$(git config branch.%(refname:short).description || :)%(color:reset),"
'

# [ -t 1 ] && color="always" || color="never"

eval "$(git for-each-ref --color="always" --format="$fmt" refs/heads)" | column -s , -t
