#!/usr/bin/env bash

# Shows branches with descriptions

cyan=$(tput setaf 6)
green=$(tput setaf 2)
normal=$(tput sgr0)
branches=$(git for-each-ref --format='%(refname:short)' refs/heads)
current_branch=$(git rev-parse --abbrev-ref HEAD)
output=""

for branch in $branches; do
	if [ "$branch" == "$current_branch" ]; then
		branch_format="* $green%-15s$normal"
	else
		branch_format="  %-15s"
	fi

	description="$cyan$(git config branch."$branch".description)$normal"
	printf -v line "$branch_format %s\\n" "$branch" "$description"
	output="$output$line"
done

printf %s "$output"
